// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuycwkjzqvtzyukjpjvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eWN3a2p6cXZ0enl1a2pwanZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODU2NDYsImV4cCI6MjA2MTE2MTY0Nn0.0QEi2EdVh015ZvQ6e1HnKSvr294TQ7tT1hRR6Yautcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);